### ISSUE TITLE
[BUG] Django fails on unrecognized languages

### ISSUE THREAD

**Issue by nilsbarth** [google/personfinder#222] opened 2015-11-30 19:58 UTC
Action: Upgrade to Django 1.9?

I believe that Django fails to initialize for an unknown language, due to missing translation.
This has apparently been fixed in Django 1.9.
Specifically, this results in this error:
'NoneType' object has no attribute '_info'

This appears to be these Django bugs, now fixed:
https://code.djangoproject.com/ticket/18192
https://code.djangoproject.com/ticket/21055
See also StackOverflow:
http://stackoverflow.com/questions/31816158/attributeerror-nonetype-object-has-no-attribute-info

**Comment by gimite** [comment] 2015-12-01 06:28
Thanks for the report. Should be fixed by #219 , so I will mark this as a duplicate of the bug.

We have implemented a workaround for this issue for zh-HK, but it doesn't seem working for zh-hk.

**Closed** 2015-12-01 06:29 UTC

**Comment by nilsbarth** [comment] 2015-12-01 15:52
Perfect, thanks!

**Comment by gimite** [comment] 2015-12-03 01:42
The latest stable version available in AppEngine is Django 1.4, so I updated to the version. Still it looks this issue is fixed. (I haven't made server release yet, though.)
